project:
  type: website

website:
  site-url: https://ninjalabo.github.io/
  repo-url: https://github.com/ninjalabo/ninjalabo.github.io
  repo-actions: [edit, issue]
  page-navigation: true
  title: "NinjaLABO"
  image: "images/logo.jpg"
  favicon: "images/favicon.png"
  google-analytics: "G-1KVB48YND6"
  page-footer: 
    left: |
      Copyright 2023-2024, NinjaLABO
    center: |
      **Get support**  

      - For pricing and sales inquiries <sales@ninjalabo.ai> 
      - Ask tech questions <help@ninjalabo.ai> 

    right: 
      - text: "Helsinki, Finland" 
      - icon: twitter
        href: https://twitter.com/ninjalabo
        aria-label: NinjaLABO Twitter
      - icon: linkedin
        href: https://www.linkedin.com/company/ninjalabo/
        aria-label: NinjaLABO LinkedIn
      - icon: github
        href: https://github.com/ninjalabo/ninjalabo.github.io
        aria-label: NinjaLABO GitHub

  twitter-card: true
  navbar:
    background: dark
    logo: "images/logo.jpg"
    logo-alt: "NinjaLABO log."
    title: false
    search: true
    left:
      - href: getstarted.qmd
        text: "Get Started"
      - text: "Resources"
        menu: 
          - href: performance.ipynb
            text: "Performance 🚀"
          - href: tutorials/runwalkthrough.qmd
            text: "Tutorials"
          - href: getstarted.qmd
            text: "Documentations"
      - text: "Company"
        menu: 
          - href: blogs/about.qmd
            text: "About"
          - href: blog.qmd#category=News
            text: "News🌟"
      - href: pricing.qmd
        text: "Pricing"
      - href: blog.qmd
        text: "Blogs🌟"
    tools:
      - icon: twitter
        href: https://twitter.com/ninjalabo
      - icon: linkedin
        href: https://www.linkedin.com/company/ninjalabo/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/ninjalabo/ninjalabo.github.io
          - text: Report a Bug
            href: https://github.com/ninjalabo/ninjalabo.github.io/issues
    right: 
      - text: "<a href='https://studio.ninjalabo.ai/' style='background-color: rgb(185, 185, 1); padding: 10px 20px; color: white; border: none; border-radius: 0.5rem; text-decoration: None; margin-right: 10px;'>Try Free</a>"
        href: getstarted.qmd
        
  sidebar:
      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - blogs/about.qmd
        - getstarted.qmd
        - section: "Tutorials"
          contents: "tutorials/*.qmd"
        - section: "Documentation"
          contents: 
          - section: "TinyMLaaS - summer 2023"
            contents: "docs/tinymlaas/*"
        # - doc.qmd
        - blog.qmd
        - performance.ipynb

format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true
